### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-stephanieggullo#1]
Good work @stephanieggullo !!

Let's improve it with these tips:

- [x] Fix the language
- [x] We need a `nav` and a `h1` tags.
- [x]  Be extra careful with syntax, it looks like you have errors when closing `li`s and `a`s
- [x] Avoid using tag selectors as `main`, switch them with class selectors.
- [x] Download the logo image, storage it on a images folder and link it from there.
- [x] Avoid uppercase on HTML texts, we can transform the text with CSS
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Improve hierarchy, we can use body tag selector to add general styles, as `color`, `background-color`, `font-family`, `font-size` and `font-weight`
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [ ] Finish the main title styles: words should jump and the typography is bolder.
- [x] Fix the main area, you have an extra white space at the bottom

And finally try to improve your commit messages, better in English and using imperative

Let me know if you have any doubts ;)

**Comment by stephanieggullo** [comment]
Hi Nasiva.
Thanks for the recomendations, I've already do and push it to the repo.

Regrads :)

**Comment by nasivuela** [comment]
Ole @stephanieggullo !!

There are still some points unclosed:

- The language of the page should be 'es' because the content is in Spanish.
- We need to add more styles to the `body` selector on CSS to improve hierarchy.
- The main title is too big and no bolder enough, it looks like you are adding the class with the styles on the parent element and no in the `h1`, and you need to import the weight fonts in the Google font link.

Go for it!

**Comment by stephanieggullo** [comment]
Hi Nasiva.
I've already do the new changes and push it to the repo.

Regrads :v:

**Comment by nasivuela** [comment]
You got it!

![](https://media.giphy.com/media/100YmlniUkSv84/giphy.gif)
